SUPPORTED_LANGUAGES = ("ru", "en")


def normalize_language(value: str | None) -> str:
    if not value:
        return "ru"
    lowered = value.lower().strip()
    if lowered.startswith("en"):
        return "en"
    if lowered.startswith("ru"):
        return "ru"
    return "ru"


def t(language: str, key: str, **kwargs: object) -> str:
    lang = normalize_language(language)
    template = MESSAGES.get(lang, MESSAGES["ru"]).get(key) or MESSAGES["ru"].get(key, key)
    return template.format(**kwargs)


MESSAGES: dict[str, dict[str, str]] = {
    "ru": {
        "rec.low.headline": "Сейчас условия благоприятные для обычной активности",
        "rec.low.summary": "Риск по жаре и воздуху низкий, можно следовать обычному распорядку.",
        "rec.low.action": "Поддерживайте обычный режим активности и гидратации.",
        "rec.moderate.headline": "Выбирайте активность в более безопасные часы",
        "rec.moderate.summary": "Условия умеренно рискованные, лучше планировать улицу точечно.",
        "rec.moderate.action1": "Сократите длительность прогулки или тренировки.",
        "rec.moderate.action2": "Избегайте пиковых часов жары.",
        "rec.moderate.action3": "Следите за самочувствием во время активности.",
        "rec.high.headline": "Сейчас лучше ограничить активность на улице",
        "rec.high.summary": "Жара и качество воздуха создают повышенную нагрузку именно для вашего профиля.",
        "rec.high.action1": "Отложите длительную активность до более безопасного окна.",
        "rec.high.action2": "Снизьте интенсивную физическую нагрузку.",
        "rec.high.action3": "Пейте больше воды и делайте частые паузы.",
        "rec.windows.closed": "Держите окна закрытыми до улучшения воздуха.",
        "rec.ventilate.window": "Проветрите в окно {start}-{end}.",
        "rec.ventilate.later": "Проветривание лучше отложить до снижения загрязнения.",
        "rec.profile.caution": "Для чувствительного профиля уменьшите время непрерывного пребывания на улице.",
        "daily.low.summary": "Условия сейчас низкого риска.",
        "daily.low.action1": "Обычная активность в целом допустима.",
        "daily.low.action2": "Поддерживайте гидратацию и обычные меры предосторожности.",
        "daily.medium.summary": "Условия умеренного риска.",
        "daily.medium.action1": "Планируйте активность в более безопасные часы.",
        "daily.medium.action2": "Следите за симптомами и остановите активность при ухудшении.",
        "daily.high.summary": "Условия высокого риска.",
        "daily.high.action1": "Ограничьте время на улице и избегайте пиковых часов жары.",
        "daily.high.action2": "Выходите на улицу короткими интервалами с перерывами.",
        "daily.high.action3": "Проветривайте, когда качество воздуха улучшится.",
        "daily.very_high.summary": "Сейчас условия очень высокого риска.",
        "daily.very_high.action1": "Избегайте активности на улице без необходимости.",
        "daily.very_high.action2": "Держите окна закрытыми в часы пикового загрязнения.",
        "daily.very_high.action3": "Чаще пейте воду и снизьте физическую нагрузку.",
        "daily.symptom.wheeze": "Недавно отмечено свистящее дыхание; снизьте нагрузку и следите за дыханием.",
        "daily.symptom.cough": "Повторяющийся кашель; выбирайте периоды с более чистым воздухом.",
        "daily.symptom.fatigue": "Есть тренд усталости; сократите тренировки и увеличьте восстановление.",
        "daily.symptom.headache": "Есть тренд головной боли; уменьшите пребывание на солнце и пейте воду.",
        "alert.disabled.title": "Уведомления отключены",
        "alert.disabled.body": "Push-уведомления отключены пользователем.",
        "alert.quiet.title": "Тихие часы",
        "alert.quiet.body": "Тихие часы активны, push не отправляется.",
        "alert.nochange.title": "Нет значимого изменения",
        "alert.nochange.body": "Риск не изменился существенно.",
        "alert.duplicate.title": "Дубликат заблокирован",
        "alert.duplicate.body": "Похожий алерт был отправлен недавно.",
        "expl.fallback": "Сейчас для вас уровень риска: {risk}. {summary} Начните с действия: {action}",
        "expl.user_instruction": "Сгенерируйте одно короткое объяснение простым языком на русском. Тон спокойный, практичный и персональный.",
        "expl.prompt.language": "Russian",
        "notification.low": "Условия низкого риска. Сохраняйте обычные меры предосторожности.",
        "notification.medium": "Условия умеренного риска. Планируйте более безопасные временные окна.",
        "notification.high": "Сейчас высокий риск по воздуху/жаре. Ограничьте активность на улице.",
        "notification.very_high": "Сейчас очень высокий риск по воздуху/жаре. Сократите пребывание на улице.",
    },
    "en": {
        "rec.low.headline": "Conditions are favorable for normal activity",
        "rec.low.summary": "Heat and air risk is currently low, regular routine is acceptable.",
        "rec.low.action": "Maintain normal activity and hydration.",
        "rec.moderate.headline": "Choose safer hours for activity",
        "rec.moderate.summary": "Conditions are moderately risky, outdoor plans should be time-aware.",
        "rec.moderate.action1": "Shorten walk or workout duration.",
        "rec.moderate.action2": "Avoid peak heat hours.",
        "rec.moderate.action3": "Monitor symptoms during activity.",
        "rec.high.headline": "It is better to limit outdoor activity now",
        "rec.high.summary": "Heat and air quality create higher load for your profile.",
        "rec.high.action1": "Delay longer activity to a safer window.",
        "rec.high.action2": "Reduce high-intensity physical effort.",
        "rec.high.action3": "Hydrate frequently and take breaks.",
        "rec.windows.closed": "Keep windows closed until air quality improves.",
        "rec.ventilate.window": "Ventilate during {start}-{end}.",
        "rec.ventilate.later": "Ventilation is better postponed until pollution drops.",
        "rec.profile.caution": "For sensitive profiles, reduce continuous outdoor exposure.",
        "daily.low.summary": "Conditions are low risk.",
        "daily.low.action1": "Normal activity is generally acceptable.",
        "daily.low.action2": "Maintain hydration and routine precautions.",
        "daily.medium.summary": "Conditions are moderate risk.",
        "daily.medium.action1": "Plan activities during safer windows.",
        "daily.medium.action2": "Monitor symptoms and stop activity if they worsen.",
        "daily.high.summary": "Conditions are high risk.",
        "daily.high.action1": "Limit outdoor time and avoid peak heat hours.",
        "daily.high.action2": "Use shorter outdoor intervals with breaks.",
        "daily.high.action3": "Prefer indoor ventilation when air quality improves.",
        "daily.very_high.summary": "Conditions are very high risk right now.",
        "daily.very_high.action1": "Avoid outdoor activity unless necessary.",
        "daily.very_high.action2": "Keep windows closed during peak pollution hours.",
        "daily.very_high.action3": "Hydrate frequently and reduce physical load.",
        "daily.symptom.wheeze": "Wheezing logged recently; reduce exertion and monitor breathing.",
        "daily.symptom.cough": "Repeated cough events detected; prioritize cleaner-air periods.",
        "daily.symptom.fatigue": "Fatigue trend detected; shorten workouts and increase recovery.",
        "daily.symptom.headache": "Headache trend detected; reduce sun exposure and stay hydrated.",
        "alert.disabled.title": "Alerts disabled",
        "alert.disabled.body": "Push alerts are disabled by user preference.",
        "alert.quiet.title": "Quiet hours",
        "alert.quiet.body": "Quiet hours are active, push is suppressed.",
        "alert.nochange.title": "No material change",
        "alert.nochange.body": "Risk has not changed significantly.",
        "alert.duplicate.title": "Duplicate blocked",
        "alert.duplicate.body": "A similar alert was sent recently.",
        "expl.fallback": "Your current risk level is {risk}. {summary} Start with: {action}",
        "expl.user_instruction": "Generate one short plain-language explanation in English. Keep tone calm, actionable, and personal.",
        "expl.prompt.language": "English",
        "notification.low": "Low risk conditions. Keep regular precautions.",
        "notification.medium": "Moderate risk conditions. Plan safer time windows.",
        "notification.high": "High air/heat risk now. Limit outdoor activity.",
        "notification.very_high": "Very high air/heat risk now. Reduce outdoor exposure.",
    },
}
