import Foundation

@MainActor
final class AppSession: ObservableObject {
    private enum Keys {
        static let onboardingCompleted = "session.onboardingCompleted"
        static let userId = "session.userId"
        static let accessToken = "session.accessToken"
        static let profileId = "session.profileId"
        static let persona = "session.persona"
        static let sensitivity = "session.sensitivity"
        static let preferredLanguage = "session.preferredLanguage"
        static let latitude = "session.latitude"
        static let longitude = "session.longitude"
    }

    @Published var onboardingCompleted = false { didSet { persist() } }
    @Published var userId = "" { didSet { persist() } }
    @Published var accessToken = "" { didSet { persist() } }
    @Published var profileId = "" { didSet { persist() } }
    @Published var persona = "adult" { didSet { persist() } }
    @Published var sensitivity = "medium" { didSet { persist() } }
    @Published var preferredLanguage = "ru" { didSet { persist() } }
    @Published var latitude = 41.39 { didSet { persist() } }
    @Published var longitude = 2.17 { didSet { persist() } }
    @Published var selectedTab = 0

    init() {
        let defaults = UserDefaults.standard
        onboardingCompleted = defaults.object(forKey: Keys.onboardingCompleted) as? Bool ?? false
        userId = defaults.string(forKey: Keys.userId) ?? ""
        accessToken = defaults.string(forKey: Keys.accessToken) ?? ""
        profileId = defaults.string(forKey: Keys.profileId) ?? ""
        persona = defaults.string(forKey: Keys.persona) ?? "adult"
        sensitivity = defaults.string(forKey: Keys.sensitivity) ?? "medium"
        preferredLanguage = defaults.string(forKey: Keys.preferredLanguage) ?? "ru"
        latitude = defaults.object(forKey: Keys.latitude) as? Double ?? 41.39
        longitude = defaults.object(forKey: Keys.longitude) as? Double ?? 2.17
    }

    func logout() {
        onboardingCompleted = false
        userId = ""
        accessToken = ""
        profileId = ""
        selectedTab = 0
    }

    private func persist() {
        let defaults = UserDefaults.standard
        defaults.set(onboardingCompleted, forKey: Keys.onboardingCompleted)
        defaults.set(userId, forKey: Keys.userId)
        defaults.set(accessToken, forKey: Keys.accessToken)
        defaults.set(profileId, forKey: Keys.profileId)
        defaults.set(persona, forKey: Keys.persona)
        defaults.set(sensitivity, forKey: Keys.sensitivity)
        defaults.set(preferredLanguage, forKey: Keys.preferredLanguage)
        defaults.set(latitude, forKey: Keys.latitude)
        defaults.set(longitude, forKey: Keys.longitude)
    }
}

enum HiAirL10n {
    static func t(_ key: String, lang: String) -> String {
        let language = lang.lowercased().hasPrefix("en") ? "en" : "ru"
        return strings[language]?[key] ?? strings["ru"]?[key] ?? key
    }

    private static let strings: [String: [String: String]] = [
        "ru": [
            "tab.dashboard": "Главная",
            "tab.planner": "План",
            "tab.insights": "Инсайты",
            "insights.empty": "Логируй симптомы, чтобы открыть персональные паттерны.",
            "insights.unlock_more": "Логируй еще 5 дней, и появятся паттерны.",
            "insights.failed": "Не удалось загрузить инсайты.",
            "insights.count": "инсайтов",
            "insights.loading": "Загружаем персональные паттерны...",
            "insights.retry": "Попробовать снова",
            "settings.briefing_setup_hint": "Сначала войди в аккаунт, чтобы настроить Morning Briefing.",
            "tab.symptoms": "Симптомы",
            "tab.settings": "Настройки",
            "auth.title": "Аккаунт HiAir",
            "auth.email": "Email",
            "auth.password": "Пароль (мин. 12 символов, A/a/0-9/символ)",
            "auth.sign_up": "Регистрация",
            "auth.signing_up": "Регистрируем...",
            "auth.log_in": "Войти",
            "auth.logging_in": "Входим...",
            "auth.enter_email": "Введите email.",
            "auth.password_short": "Пароль должен быть не короче 12 символов.",
            "auth.ok": "Авторизация успешна.",
            "auth.fail": "Ошибка авторизации.",
            "onboarding.title": "Онбординг HiAir",
            "onboarding.persona": "Профиль",
            "onboarding.sensitivity": "Чувствительность",
            "onboarding.latitude": "Широта",
            "onboarding.longitude": "Долгота",
            "onboarding.profile_id": "Profile ID (необязательно)",
            "onboarding.continue": "Продолжить",
            "dashboard.title": "Ежедневный воздушный интеллект",
            "common.city_updated": "Barcelona • Обновлено 2 мин назад",
            "dashboard.subtitle": "Риск, алерты и AI-инсайты в одном месте.",
            "dashboard.greeting": "Доброе утро, Alex",
            "dashboard.improving": "Качество воздуха улучшается. Планируйте прогулку после 16:30.",
            "dashboard.current_risk": "Текущий риск",
            "dashboard.current_risk_title": "Текущий риск",
            "dashboard.badge_moderate": "УМЕРЕННЫЙ",
            "dashboard.reason_code": "Жара + озон формируют текущий риск.",
            "dashboard.tomorrow_hint": "Завтра риск вероятно вырастет на 6 пунктов из-за скачка влажности.",
            "dashboard.location": "Barcelona",
            "dashboard.freshness_fresh": "свежее",
            "dashboard.freshness_stale": "обновить",
            "dashboard.profile_button": "Профиль",
            "dashboard.no_safe_window": "Нет безопасных окон в ближайшие часы.",
            "dashboard.error": "Не удалось загрузить данные.",
            "dashboard.recommended_actions": "Рекомендуемые действия",
            "dashboard.no_actions": "Нет доступных действий.",
            "dashboard.safe_window": "Безопасное окно",
            "dashboard.safe_windows": "Безопасные окна",
            "dashboard.auto_updates": "Автообновление по прогнозу",
            "dashboard.do_now": "Сделать сейчас",
            "dashboard.action_1": "Избегайте активности с 10:00 до 15:00",
            "dashboard.action_2": "Пейте воду каждые 45 минут",
            "dashboard.action_3": "Лучшая прогулка: 16:30 - 19:00",
            "dashboard.recompute": "Пересчитать риск сейчас",
            "dashboard.log_symptoms": "Записать симптомы",
            "dashboard.loading": "Загрузка...",
            "planner.title": "План дня",
            "planner.subtitle": "Полный план на основе профиля и качества воздуха.",
            "planner.safe_windows": "Безопасные окна",
            "planner.ventilation_windows": "Окна проветривания",
            "planner.hourly_risk": "Риск по часам",
            "planner.hourly": "Почасово",
            "planner.refresh": "Обновить план",
            "planner.apply": "Применить план",
            "planner.loading": "Загрузка...",
            "planner.profile_required": "Нужен Profile ID.",
            "planner.failed": "Не удалось загрузить план.",
            "symptoms.title": "Журнал симптомов",
            "symptoms.subtitle": "Отмечайте самочувствие для точных персональных рекомендаций.",
            "symptoms.streak": "Серия: 4 дня подряд",
            "symptoms.profile_id": "Profile ID",
            "symptoms.cough": "Кашель",
            "symptoms.wheeze": "Свистящее дыхание",
            "symptoms.headache": "Головная боль",
            "symptoms.fatigue": "Усталость",
            "symptoms.sleep_quality": "Качество сна",
            "symptoms.quick_intensity": "Интенсивность (быстро)",
            "symptoms.quick_breath": "Быстро: Дыхание",
            "symptoms.quick_headache": "Быстро: Голова",
            "symptoms.save": "Сохранить симптомы",
            "symptoms.submit": "Отправить симптомы",
            "symptoms.saving": "Сохраняем...",
            "symptoms.saved_at": "Сохранено в",
            "symptoms.save_failed": "Не удалось сохранить симптомы.",
            "symptoms.quick_saved": "Быстрый симптом сохранён.",
            "symptoms.quick_failed": "Не удалось сохранить быстрый симптом.",
            "settings.ai_observability": "AI наблюдаемость",
            "settings.subtitle": "Управляйте уведомлениями, подпиской и AI-наблюдаемостью.",
            "settings.notifications": "Уведомления",
            "settings.push": "Включить push-уведомления",
            "settings.morning_briefing": "Morning Briefing",
            "settings.morning_briefing_time": "Время брифинга (HH:MM)",
            "settings.morning_briefing_hint": "Персональная сводка каждое утро.",
            "settings.profile_alerting": "Алерты с учетом профиля",
            "settings.alert_threshold": "Порог алерта",
            "settings.threshold_medium": "Средний",
            "settings.threshold_high": "Высокий",
            "settings.threshold_very_high": "Очень высокий",
            "settings.quiet_start": "Тихие часы: начало",
            "settings.quiet_end": "Тихие часы: конец",
            "settings.profile_defaults": "Профиль по умолчанию",
            "settings.persona": "Персона",
            "settings.persona_adult": "Взрослый",
            "settings.persona_child": "Ребенок",
            "settings.persona_elderly": "Пожилой",
            "settings.persona_asthma": "Астма",
            "settings.persona_allergy": "Аллергия",
            "settings.persona_runner": "Бегун",
            "settings.persona_worker": "Рабочий на улице",
            "settings.language": "Язык",
            "settings.language_ru": "Русский",
            "settings.language_en": "English",
            "settings.window_24h": "24ч",
            "settings.window_72h": "72ч",
            "settings.sync": "Синхронизация",
            "settings.loading": "Загрузка...",
            "settings.saving": "Сохраняем...",
            "settings.subscription": "Подписка",
            "settings.security_privacy": "Безопасность и приватность",
            "settings.plan": "План",
            "settings.status": "Статус",
            "settings.sync_now": "Сохранить настройки и синхронизировать",
            "settings.advanced_controls": "Расширенные параметры графика",
            "settings.load": "Загрузить настройки",
            "settings.save": "Сохранить настройки",
            "settings.load_plans": "Загрузить планы",
            "settings.load_subscription": "Загрузить подписку",
            "settings.activate_subscription": "Активировать подписку",
            "settings.cancel_subscription": "Отменить подписку",
            "settings.user_id_required": "Введите User ID.",
            "settings.loaded": "Настройки загружены.",
            "settings.load_failed": "Не удалось загрузить настройки.",
            "settings.saved": "Настройки сохранены.",
            "settings.save_failed": "Не удалось сохранить настройки.",
            "settings.plans_loaded": "Планы загружены.",
            "settings.plans_load_failed": "Не удалось загрузить планы.",
            "settings.subscription_loaded": "Подписка загружена.",
            "settings.subscription_load_failed": "Не удалось загрузить подписку.",
            "settings.subscription_activated": "Подписка активирована.",
            "settings.subscription_activate_failed": "Не удалось активировать подписку.",
            "settings.subscription_canceled": "Подписка отменена.",
            "settings.subscription_cancel_failed": "Не удалось отменить подписку.",
            "settings.subscription_status_active": "активна",
            "settings.subscription_status_inactive": "неактивна",
            "settings.subscription_status_canceled": "отменена",
            "settings.logged_out": "Вы вышли из аккаунта.",
            "settings.log_out": "Выйти",
            "settings.user_id": "User ID",
            "settings.token": "Access token",
            "settings.window": "Окно",
            "settings.metric": "Метрика",
            "settings.metric.total": "Всего",
            "settings.metric.fallback": "Fallback",
            "settings.metric.guardrail": "Guardrail",
            "settings.metric.errors": "Ошибки (сумма)",
            "settings.metric.timeout": "Таймаут",
            "settings.metric.network": "Сеть",
            "settings.metric.server": "Сервер",
            "settings.mode": "Режим",
            "settings.mode.bars": "Столбцы",
            "settings.mode.line": "Линия",
            "settings.range": "Диапазон",
            "settings.axis": "Ось",
            "settings.request_status": "Статус запроса",
            "settings.request_loading": "Загрузка...",
            "settings.request_idle": "Ожидание",
            "settings.request_timeout": "Таймаут",
            "settings.last_updated": "Последнее обновление",
            "settings.ai_retry_now": "Повторить сейчас",
            "settings.ai_retry_later": "Повторить позже",
            "settings.ai_timeout_inline": "Превышено время ожидания AI запроса.",
            "settings.ai_network_inline": "Нет сети. Проверьте подключение и попробуйте снова.",
            "settings.ai_server_inline": "Сервер временно недоступен. Попробуйте позже.",
            "settings.ai_request_failed_inline": "Ошибка запроса AI наблюдаемости.",
            "settings.ai_top_prompt": "Топ версия промпта",
            "settings.ai_top_model": "Топ модель",
            "settings.ai_error_counts": "Ошибки",
            "settings.ai_error_type.timeout": "таймаут",
            "settings.ai_error_type.network": "сеть",
            "settings.ai_error_type.server": "сервер",
            "settings.ai_error_type.other": "прочее",
            "settings.ai_events": "AI события",
            "settings.ai_fallback": "fallback",
            "settings.ai_guardrail_blocks": "блокировки guardrail",
            "settings.ai_latest_hour": "Последний час",
            "settings.ai_blocks_short": "блоки",
            "settings.ai_no_trend": "Для выбранного периода нет точек тренда.",
            "settings.ai_loaded": "AI наблюдаемость загружена.",
            "settings.ai_failed": "Не удалось загрузить AI наблюдаемость.",
            "settings.ai_request_failed": "Запрос AI наблюдаемости завершился ошибкой.",
            "settings.load_ai_summary": "Загрузить AI сводку",
            "settings.loading_ai_metrics": "Загружаем AI метрики..."
        ],
        "en": [
            "tab.dashboard": "Dashboard",
            "tab.planner": "Planner",
            "tab.insights": "Insights",
            "insights.empty": "Log symptoms to unlock personal patterns.",
            "insights.unlock_more": "Log 5 more days to unlock patterns.",
            "insights.failed": "Failed to load insights.",
            "insights.count": "insights",
            "insights.loading": "Loading personal patterns...",
            "insights.retry": "Try again",
            "settings.briefing_setup_hint": "Sign in first to configure Morning Briefing.",
            "tab.symptoms": "Symptoms",
            "tab.settings": "Settings",
            "auth.title": "HiAir Account",
            "auth.email": "Email",
            "auth.password": "Password (min 12 chars, A/a/0-9/symbol)",
            "auth.sign_up": "Sign Up",
            "auth.signing_up": "Signing up...",
            "auth.log_in": "Log In",
            "auth.logging_in": "Logging in...",
            "auth.enter_email": "Enter email.",
            "auth.password_short": "Password must be at least 12 characters.",
            "auth.ok": "Authenticated.",
            "auth.fail": "Auth failed.",
            "onboarding.title": "HiAir Onboarding",
            "onboarding.persona": "Persona",
            "onboarding.sensitivity": "Sensitivity",
            "onboarding.latitude": "Latitude",
            "onboarding.longitude": "Longitude",
            "onboarding.profile_id": "Profile ID (optional)",
            "onboarding.continue": "Continue",
            "dashboard.title": "Daily Air Intelligence",
            "common.city_updated": "Barcelona • Updated 2 min ago",
            "dashboard.subtitle": "Live risk, alerts and AI insights in one place.",
            "dashboard.greeting": "Good morning, Alex",
            "dashboard.improving": "Air quality is improving. Plan outdoors after 16:30.",
            "dashboard.current_risk": "Current risk",
            "dashboard.current_risk_title": "Current risk",
            "dashboard.badge_moderate": "MODERATE",
            "dashboard.reason_code": "Heat + ozone are driving today's risk.",
            "dashboard.tomorrow_hint": "Tomorrow risk may rise by 6 points due to a humidity spike.",
            "dashboard.location": "Barcelona",
            "dashboard.freshness_fresh": "fresh",
            "dashboard.freshness_stale": "refresh",
            "dashboard.profile_button": "Profile",
            "dashboard.no_safe_window": "No safe windows in the next hours.",
            "dashboard.error": "Unable to load data.",
            "dashboard.recommended_actions": "Recommended actions",
            "dashboard.no_actions": "No actions available.",
            "dashboard.safe_window": "Safe window",
            "dashboard.safe_windows": "Safe windows",
            "dashboard.auto_updates": "Auto-updates by forecast",
            "dashboard.do_now": "Do this now",
            "dashboard.action_1": "Avoid direct sun from 10:00 to 15:00",
            "dashboard.action_2": "Hydrate every 45 minutes",
            "dashboard.action_3": "Best outdoor window 16:30 - 19:00",
            "dashboard.recompute": "Recompute risk now",
            "dashboard.log_symptoms": "Log symptoms now",
            "dashboard.loading": "Loading...",
            "planner.title": "Daily Planner",
            "planner.subtitle": "Complete recommendations based on your profile and air trends.",
            "planner.safe_windows": "Safe windows",
            "planner.ventilation_windows": "Ventilation windows",
            "planner.hourly_risk": "Hourly risk",
            "planner.hourly": "Hour-by-hour",
            "planner.refresh": "Refresh planner",
            "planner.apply": "Apply this plan",
            "planner.loading": "Loading...",
            "planner.profile_required": "Profile ID is required.",
            "planner.failed": "Failed to load planner.",
            "symptoms.title": "Symptoms Log",
            "symptoms.subtitle": "Track how you feel for better personalized guidance.",
            "symptoms.streak": "Streak: 4 days in a row",
            "symptoms.profile_id": "Profile ID",
            "symptoms.cough": "Cough",
            "symptoms.wheeze": "Wheeze",
            "symptoms.headache": "Headache",
            "symptoms.fatigue": "Fatigue",
            "symptoms.sleep_quality": "Sleep quality",
            "symptoms.quick_intensity": "Quick intensity",
            "symptoms.quick_breath": "Quick: Breath",
            "symptoms.quick_headache": "Quick: Headache",
            "symptoms.save": "Save Symptoms",
            "symptoms.submit": "Submit symptoms",
            "symptoms.saving": "Saving...",
            "symptoms.saved_at": "Saved at",
            "symptoms.save_failed": "Failed to save symptoms.",
            "symptoms.quick_saved": "Quick symptom saved.",
            "symptoms.quick_failed": "Failed to save quick symptom.",
            "settings.ai_observability": "AI Observability",
            "settings.subtitle": "Manage notifications, subscriptions and AI observability.",
            "settings.notifications": "Notifications",
            "settings.push": "Enable push alerts",
            "settings.morning_briefing": "Morning Briefing",
            "settings.morning_briefing_time": "Briefing time (HH:MM)",
            "settings.morning_briefing_hint": "Personal summary delivered every morning.",
            "settings.profile_alerting": "Profile-based alerting",
            "settings.alert_threshold": "Alert threshold",
            "settings.threshold_medium": "Medium",
            "settings.threshold_high": "High",
            "settings.threshold_very_high": "Very high",
            "settings.quiet_start": "Quiet start",
            "settings.quiet_end": "Quiet end",
            "settings.profile_defaults": "Profile defaults",
            "settings.persona": "Persona",
            "settings.persona_adult": "Adult",
            "settings.persona_child": "Child",
            "settings.persona_elderly": "Elderly",
            "settings.persona_asthma": "Asthma",
            "settings.persona_allergy": "Allergy",
            "settings.persona_runner": "Runner",
            "settings.persona_worker": "Outdoor worker",
            "settings.language": "Language",
            "settings.language_ru": "Russian",
            "settings.language_en": "English",
            "settings.window_24h": "24h",
            "settings.window_72h": "72h",
            "settings.sync": "Sync",
            "settings.loading": "Loading...",
            "settings.saving": "Saving...",
            "settings.subscription": "Subscription",
            "settings.security_privacy": "Security & Privacy",
            "settings.plan": "Plan",
            "settings.status": "Status",
            "settings.sync_now": "Save settings & sync",
            "settings.advanced_controls": "Advanced chart controls",
            "settings.load": "Load settings",
            "settings.save": "Save settings",
            "settings.load_plans": "Load plans",
            "settings.load_subscription": "Load subscription",
            "settings.activate_subscription": "Activate subscription",
            "settings.cancel_subscription": "Cancel subscription",
            "settings.user_id_required": "Enter user ID.",
            "settings.loaded": "Settings loaded.",
            "settings.load_failed": "Failed to load settings.",
            "settings.saved": "Settings saved.",
            "settings.save_failed": "Failed to save settings.",
            "settings.plans_loaded": "Plans loaded.",
            "settings.plans_load_failed": "Failed to load plans.",
            "settings.subscription_loaded": "Subscription loaded.",
            "settings.subscription_load_failed": "Failed to load subscription.",
            "settings.subscription_activated": "Subscription activated.",
            "settings.subscription_activate_failed": "Failed to activate subscription.",
            "settings.subscription_canceled": "Subscription canceled.",
            "settings.subscription_cancel_failed": "Failed to cancel subscription.",
            "settings.subscription_status_active": "active",
            "settings.subscription_status_inactive": "inactive",
            "settings.subscription_status_canceled": "canceled",
            "settings.logged_out": "Logged out.",
            "settings.log_out": "Log out",
            "settings.user_id": "User ID",
            "settings.token": "Access token",
            "settings.window": "Window",
            "settings.metric": "Metric",
            "settings.metric.total": "Total",
            "settings.metric.fallback": "Fallback",
            "settings.metric.guardrail": "Guardrail",
            "settings.metric.errors": "Errors (sum)",
            "settings.metric.timeout": "Timeout",
            "settings.metric.network": "Network",
            "settings.metric.server": "Server",
            "settings.mode": "Mode",
            "settings.mode.bars": "Bars",
            "settings.mode.line": "Line",
            "settings.range": "Range",
            "settings.axis": "Axis",
            "settings.request_status": "Request status",
            "settings.request_loading": "Loading...",
            "settings.request_idle": "Idle",
            "settings.request_timeout": "Timeout",
            "settings.last_updated": "Last updated",
            "settings.ai_retry_now": "Retry now",
            "settings.ai_retry_later": "Try later",
            "settings.ai_timeout_inline": "AI observability request timed out.",
            "settings.ai_network_inline": "Network unavailable. Check your connection and retry.",
            "settings.ai_server_inline": "Server is temporarily unavailable. Please try later.",
            "settings.ai_request_failed_inline": "AI observability request failed.",
            "settings.ai_top_prompt": "Top prompt version",
            "settings.ai_top_model": "Top model",
            "settings.ai_error_counts": "Errors",
            "settings.ai_error_type.timeout": "timeout",
            "settings.ai_error_type.network": "network",
            "settings.ai_error_type.server": "server",
            "settings.ai_error_type.other": "other",
            "settings.ai_events": "AI events",
            "settings.ai_fallback": "fallback",
            "settings.ai_guardrail_blocks": "guardrail blocks",
            "settings.ai_latest_hour": "Latest hour",
            "settings.ai_blocks_short": "blocks",
            "settings.ai_no_trend": "No trend points for selected period.",
            "settings.ai_loaded": "AI observability loaded.",
            "settings.ai_failed": "Failed to load AI observability.",
            "settings.ai_request_failed": "AI observability request failed.",
            "settings.load_ai_summary": "Load AI Summary",
            "settings.loading_ai_metrics": "Loading AI metrics..."
        ]
    ]
}

extension AppSession {
    func l(_ key: String) -> String {
        HiAirL10n.t(key, lang: preferredLanguage)
    }
}
