import Foundation

@MainActor
final class AppSession: ObservableObject {
    private enum Keys {
        static let onboardingCompleted = "session.onboardingCompleted"
        static let isGuest = "session.isGuest"
        static let healthOptIn = "session.healthOptIn"
        static let userId = "session.userId"
        static let accessToken = "session.accessToken"
        static let profileId = "session.profileId"
        static let persona = "session.persona"
        static let sensitivity = "session.sensitivity"
        static let preferredLanguage = "session.preferredLanguage"
        static let latitude = "session.latitude"
        static let longitude = "session.longitude"
    }

    @Published var onboardingCompleted = false { didSet { persist() } }
    @Published var isGuest = false { didSet { persist() } }
    @Published var healthOptIn = false { didSet { persist() } }
    @Published var userId = "" { didSet { persist() } }
    @Published var accessToken = "" { didSet { persist() } }
    @Published var profileId = "" { didSet { persist() } }
    @Published var persona = "adult" { didSet { persist() } }
    @Published var sensitivity = "medium" { didSet { persist() } }
    @Published var preferredLanguage = "ru" { didSet { persist() } }
    @Published var latitude = 41.39 { didSet { persist() } }
    @Published var longitude = 2.17 { didSet { persist() } }
    @Published var selectedTab = 0

    init() {
        let defaults = UserDefaults.standard
        onboardingCompleted = defaults.object(forKey: Keys.onboardingCompleted) as? Bool ?? false
        isGuest = defaults.object(forKey: Keys.isGuest) as? Bool ?? false
        healthOptIn = defaults.object(forKey: Keys.healthOptIn) as? Bool ?? false
        userId = defaults.string(forKey: Keys.userId) ?? ""
        accessToken = defaults.string(forKey: Keys.accessToken) ?? ""
        profileId = defaults.string(forKey: Keys.profileId) ?? ""
        persona = defaults.string(forKey: Keys.persona) ?? "adult"
        sensitivity = defaults.string(forKey: Keys.sensitivity) ?? "medium"
        preferredLanguage = defaults.string(forKey: Keys.preferredLanguage) ?? "ru"
        latitude = defaults.object(forKey: Keys.latitude) as? Double ?? 41.39
        longitude = defaults.object(forKey: Keys.longitude) as? Double ?? 2.17
    }

    func logout() {
        onboardingCompleted = false
        userId = ""
        accessToken = ""
        profileId = ""
        selectedTab = 0
    }

    private func persist() {
        let defaults = UserDefaults.standard
        defaults.set(onboardingCompleted, forKey: Keys.onboardingCompleted)
        defaults.set(isGuest, forKey: Keys.isGuest)
        defaults.set(healthOptIn, forKey: Keys.healthOptIn)
        defaults.set(userId, forKey: Keys.userId)
        defaults.set(accessToken, forKey: Keys.accessToken)
        defaults.set(profileId, forKey: Keys.profileId)
        defaults.set(persona, forKey: Keys.persona)
        defaults.set(sensitivity, forKey: Keys.sensitivity)
        defaults.set(preferredLanguage, forKey: Keys.preferredLanguage)
        defaults.set(latitude, forKey: Keys.latitude)
        defaults.set(longitude, forKey: Keys.longitude)
    }
}

enum HiAirL10n {
    static func t(_ key: String, lang: String) -> String {
        let language = lang.lowercased().hasPrefix("en") ? "en" : "ru"
        return strings[language]?[key] ?? strings["ru"]?[key] ?? key
    }

    private static let strings: [String: [String: String]] = [
        "ru": [
            "tab.dashboard": "Главная",
            "tab.planner": "План",
            "tab.symptoms": "Симптомы",
            "tab.settings": "Настройки",
            "auth.title": "Аккаунт HiAir",
            "auth.email": "Email",
            "auth.password": "Пароль (мин. 8 символов)",
            "auth.sign_up": "Регистрация",
            "auth.signing_up": "Регистрируем...",
            "auth.log_in": "Войти",
            "auth.logging_in": "Входим...",
            "auth.enter_email": "Введите email.",
            "auth.password_short": "Пароль должен быть не короче 8 символов.",
            "auth.ok": "Авторизация успешна.",
            "auth.fail": "Ошибка авторизации.",
            "onboarding.title": "Онбординг HiAir",
            "onboarding.persona": "Профиль",
            "onboarding.sensitivity": "Чувствительность",
            "onboarding.latitude": "Широта",
            "onboarding.longitude": "Долгота",
            "onboarding.profile_id": "Profile ID (необязательно)",
            "onboarding.continue": "Продолжить",
            "onboarding.continue_guest": "Продолжить как гость",
            "onboarding.skip": "Пропустить",
            "onboarding.enable_health": "Подключить (optional)",
            "onboarding.finish": "Перейти в приложение",
            "onboarding.welcome_headline": "HiAir — wellness-ассистент по жаре и воздуху",
            "onboarding.welcome_body": "Персональный риск, безопасные окна и ежедневные рекомендации.",
            "onboarding.value_headline": "Что вы получите",
            "onboarding.value_body": "HiAir объясняет риск жары и AQI для вашего профиля.",
            "onboarding.persona_headline": "Кто вы?",
            "onboarding.persona_body": "Wellness-ориентир, не медицинский диагноз.",
            "onboarding.location_headline": "Где вы находитесь?",
            "onboarding.location_body": "Локация нужна для прогноза жары и AQI.",
            "onboarding.notifications_headline": "Уведомления о риске",
            "onboarding.notifications_body": "Предупреждения при повышении риска для вашего профиля.",
            "onboarding.health_headline": "Данные здоровья (optional)",
            "onboarding.health_body": "Шаги, пульс и сон помогут персонализации позже (foundation).",
            "onboarding.health_optional": "HiAir — wellness guidance, not medical advice.",
            "onboarding.first_result_headline": "Ваш первый результат",
            "onboarding.step.welcome": "Шаг 1 из 7",
            "onboarding.step.value": "Шаг 2 из 7",
            "onboarding.step.persona": "Шаг 3 из 7",
            "onboarding.step.location": "Шаг 4 из 7",
            "onboarding.step.notifications": "Шаг 5 из 7",
            "onboarding.step.health": "Шаг 6 из 7",
            "onboarding.step.first_result": "Шаг 7 из 7",
            "dashboard.morning_briefing": "Утренний брифинг",
            "dashboard.risk_breakdown": "Из чего складывается риск",
            "dashboard.share": "Поделиться",
            "dashboard.fetch": "Нажмите обновить для загрузки данных.",
            "dashboard.no_actions": "Нет доступных действий.",
            "privacy.title": "Приватность",
            "privacy.export": "Экспорт моих данных",
            "privacy.delete": "Удалить мои данные",
            "privacy.wellness_notice": "HiAir — wellness guidance, not medical advice.",
            "privacy.health_explanation": "Данные HealthKit optional. Сейчас только foundation — чтение метрик после entitlements.",
            "privacy.policy": "Privacy Policy",
            "privacy.terms": "Terms of Service",
            "privacy.auth_required": "Для export/delete нужен вход в аккаунт (не guest).",
            "privacy.export_ok": "Экспорт выполнен.",
            "privacy.export_failed": "Не удалось экспортировать данные.",
            "privacy.delete_ok": "Данные удалены.",
            "privacy.delete_failed": "Не удалось удалить данные.",
            "privacy.delete_confirm_title": "Удалить все данные?",
            "privacy.delete_confirm_body": "Это необратимо. На сервере требуется подтверждение DELETE.",
            "privacy.delete_confirm_yes": "Удалить",
            "privacy.delete_confirm_no": "Отмена",
            "health.foundation_only": "Foundation only: чтение шагов/пульса/сна будет после entitlements и device QA.",
            "health.skipped": "Данные здоровья не используются.",
            "health.not_available": "HealthKit недоступен.",
            "health.permission_needed": "Разрешения HealthKit можно включить позже.",
            "share.title": "HiAir — air & heat risk",
            "share.risk": "Риск",
            "share.best_walk": "Лучшее время для прогулки",
            "share.warning": "Предупреждение",
            "share.generated_by": "Generated by HiAir",
            "dashboard.title": "Ежедневный воздушный интеллект",
            "common.city_updated": "Barcelona • Обновлено 2 мин назад",
            "dashboard.subtitle": "Риск, алерты и AI-инсайты в одном месте.",
            "dashboard.greeting": "Доброе утро, Alex",
            "dashboard.improving": "Качество воздуха улучшается. Планируйте прогулку после 16:30.",
            "dashboard.current_risk": "Текущий риск",
            "dashboard.current_risk_title": "Текущий риск",
            "dashboard.badge_moderate": "УМЕРЕННЫЙ",
            "dashboard.no_safe_window": "Нет безопасных окон в ближайшие часы.",
            "dashboard.error": "Не удалось загрузить данные.",
            "dashboard.recommended_actions": "Рекомендуемые действия",
            "dashboard.no_actions": "Нет доступных действий.",
            "dashboard.safe_window": "Безопасное окно",
            "dashboard.safe_windows": "Безопасные окна",
            "dashboard.auto_updates": "Автообновление по прогнозу",
            "dashboard.do_now": "Сделать сейчас",
            "dashboard.action_1": "Избегайте активности с 10:00 до 15:00",
            "dashboard.action_2": "Пейте воду каждые 45 минут",
            "dashboard.action_3": "Лучшая прогулка: 16:30 - 19:00",
            "dashboard.recompute": "Пересчитать риск сейчас",
            "dashboard.log_symptoms": "Записать симптомы",
            "dashboard.loading": "Загрузка...",
            "planner.title": "План дня",
            "planner.subtitle": "Полный план на основе профиля и качества воздуха.",
            "planner.safe_windows": "Безопасные окна",
            "planner.ventilation_windows": "Окна проветривания",
            "planner.hourly_risk": "Риск по часам",
            "planner.hourly": "Почасово",
            "planner.refresh": "Обновить план",
            "planner.apply": "Применить план",
            "planner.loading": "Загрузка...",
            "planner.profile_required": "Нужен Profile ID.",
            "planner.failed": "Не удалось загрузить план.",
            "symptoms.title": "Журнал симптомов",
            "symptoms.subtitle": "Отмечайте самочувствие для точных персональных рекомендаций.",
            "symptoms.profile_id": "Profile ID",
            "symptoms.cough": "Кашель",
            "symptoms.wheeze": "Свистящее дыхание",
            "symptoms.headache": "Головная боль",
            "symptoms.fatigue": "Усталость",
            "symptoms.sleep_quality": "Качество сна",
            "symptoms.quick_intensity": "Интенсивность (быстро)",
            "symptoms.quick_breath": "Быстро: Дыхание",
            "symptoms.quick_headache": "Быстро: Голова",
            "symptoms.save": "Сохранить симптомы",
            "symptoms.submit": "Отправить симптомы",
            "symptoms.saving": "Сохраняем...",
            "symptoms.saved_at": "Сохранено в",
            "symptoms.save_failed": "Не удалось сохранить симптомы.",
            "symptoms.quick_saved": "Быстрый симптом сохранён.",
            "symptoms.quick_failed": "Не удалось сохранить быстрый симптом.",
            "settings.ai_observability": "AI наблюдаемость",
            "settings.subtitle": "Управляйте уведомлениями, подпиской и AI-наблюдаемостью.",
            "settings.notifications": "Уведомления",
            "settings.push": "Включить push-уведомления",
            "settings.profile_alerting": "Алерты с учетом профиля",
            "settings.alert_threshold": "Порог алерта",
            "settings.threshold_medium": "Средний",
            "settings.threshold_high": "Высокий",
            "settings.threshold_very_high": "Очень высокий",
            "settings.quiet_start": "Тихие часы: начало",
            "settings.quiet_end": "Тихие часы: конец",
            "settings.profile_defaults": "Профиль по умолчанию",
            "settings.persona": "Персона",
            "settings.persona_adult": "Взрослый",
            "settings.persona_child": "Ребенок",
            "settings.persona_elderly": "Пожилой",
            "settings.persona_asthma": "Астма",
            "settings.persona_allergy": "Аллергия",
            "settings.persona_runner": "Бегун",
            "settings.persona_worker": "Рабочий на улице",
            "settings.language": "Язык",
            "settings.language_ru": "Русский",
            "settings.language_en": "English",
            "settings.window_24h": "24ч",
            "settings.window_72h": "72ч",
            "settings.sync": "Синхронизация",
            "settings.loading": "Загрузка...",
            "settings.saving": "Сохраняем...",
            "settings.subscription": "Подписка",
            "settings.security_privacy": "Безопасность и приватность",
            "settings.plan": "План",
            "settings.status": "Статус",
            "settings.sync_now": "Сохранить настройки и синхронизировать",
            "settings.advanced_controls": "Расширенные параметры графика",
            "settings.load": "Загрузить настройки",
            "settings.save": "Сохранить настройки",
            "settings.load_plans": "Загрузить планы",
            "settings.load_subscription": "Загрузить подписку",
            "settings.activate_subscription": "Активировать подписку",
            "settings.cancel_subscription": "Отменить подписку",
            "settings.user_id_required": "Введите User ID.",
            "settings.loaded": "Настройки загружены.",
            "settings.load_failed": "Не удалось загрузить настройки.",
            "settings.saved": "Настройки сохранены.",
            "settings.save_failed": "Не удалось сохранить настройки.",
            "settings.plans_loaded": "Планы загружены.",
            "settings.plans_load_failed": "Не удалось загрузить планы.",
            "settings.subscription_loaded": "Подписка загружена.",
            "settings.subscription_load_failed": "Не удалось загрузить подписку.",
            "settings.subscription_activated": "Подписка активирована.",
            "settings.subscription_activate_failed": "Не удалось активировать подписку.",
            "settings.subscription_canceled": "Подписка отменена.",
            "settings.subscription_cancel_failed": "Не удалось отменить подписку.",
            "settings.subscription_status_active": "активна",
            "settings.subscription_status_inactive": "неактивна",
            "settings.subscription_status_canceled": "отменена",
            "settings.logged_out": "Вы вышли из аккаунта.",
            "settings.log_out": "Выйти",
            "settings.user_id": "User ID",
            "settings.token": "Access token",
            "settings.window": "Окно",
            "settings.metric": "Метрика",
            "settings.metric.total": "Всего",
            "settings.metric.fallback": "Fallback",
            "settings.metric.guardrail": "Guardrail",
            "settings.metric.errors": "Ошибки (сумма)",
            "settings.metric.timeout": "Таймаут",
            "settings.metric.network": "Сеть",
            "settings.metric.server": "Сервер",
            "settings.mode": "Режим",
            "settings.mode.bars": "Столбцы",
            "settings.mode.line": "Линия",
            "settings.range": "Диапазон",
            "settings.axis": "Ось",
            "settings.request_status": "Статус запроса",
            "settings.request_loading": "Загрузка...",
            "settings.request_idle": "Ожидание",
            "settings.request_timeout": "Таймаут",
            "settings.last_updated": "Последнее обновление",
            "settings.ai_retry_now": "Повторить сейчас",
            "settings.ai_retry_later": "Повторить позже",
            "settings.ai_timeout_inline": "Превышено время ожидания AI запроса.",
            "settings.ai_network_inline": "Нет сети. Проверьте подключение и попробуйте снова.",
            "settings.ai_server_inline": "Сервер временно недоступен. Попробуйте позже.",
            "settings.ai_request_failed_inline": "Ошибка запроса AI наблюдаемости.",
            "settings.ai_top_prompt": "Топ версия промпта",
            "settings.ai_top_model": "Топ модель",
            "settings.ai_error_counts": "Ошибки",
            "settings.ai_error_type.timeout": "таймаут",
            "settings.ai_error_type.network": "сеть",
            "settings.ai_error_type.server": "сервер",
            "settings.ai_error_type.other": "прочее",
            "settings.ai_events": "AI события",
            "settings.ai_fallback": "fallback",
            "settings.ai_guardrail_blocks": "блокировки guardrail",
            "settings.ai_latest_hour": "Последний час",
            "settings.ai_blocks_short": "блоки",
            "settings.ai_no_trend": "Для выбранного периода нет точек тренда.",
            "settings.ai_loaded": "AI наблюдаемость загружена.",
            "settings.ai_failed": "Не удалось загрузить AI наблюдаемость.",
            "settings.ai_request_failed": "Запрос AI наблюдаемости завершился ошибкой.",
            "settings.load_ai_summary": "Загрузить AI сводку",
            "settings.loading_ai_metrics": "Загружаем AI метрики...",
            "feedback.title": "Отправить отзыв",
            "feedback.subtitle": "Помогите нам улучшить HiAir для первых пользователей.",
            "feedback.liked": "Что понравилось",
            "feedback.confusing": "Что непонятно",
            "feedback.broken": "Что сломалось",
            "feedback.email_optional": "Email (необязательно)",
            "feedback.send": "Отправить",
            "feedback.sent_ok": "Спасибо! Отзыв отправлен.",
            "feedback.sent_failed": "Не удалось отправить отзыв.",
            "feedback.empty": "Заполните хотя бы одно поле.",
            "kpi.load": "KPI (первые пользователи)",
            "kpi.load_failed": "Не удалось загрузить KPI."
        ],
        "en": [
            "tab.dashboard": "Dashboard",
            "tab.planner": "Planner",
            "tab.symptoms": "Symptoms",
            "tab.settings": "Settings",
            "auth.title": "HiAir Account",
            "auth.email": "Email",
            "auth.password": "Password (min 8 chars)",
            "auth.sign_up": "Sign Up",
            "auth.signing_up": "Signing up...",
            "auth.log_in": "Log In",
            "auth.logging_in": "Logging in...",
            "auth.enter_email": "Enter email.",
            "auth.password_short": "Password must be at least 8 characters.",
            "auth.ok": "Authenticated.",
            "auth.fail": "Auth failed.",
            "onboarding.title": "HiAir Onboarding",
            "onboarding.persona": "Persona",
            "onboarding.sensitivity": "Sensitivity",
            "onboarding.latitude": "Latitude",
            "onboarding.longitude": "Longitude",
            "onboarding.profile_id": "Profile ID (optional)",
            "onboarding.continue": "Continue",
            "onboarding.continue_guest": "Continue as guest",
            "onboarding.skip": "Skip",
            "onboarding.enable_health": "Connect (optional)",
            "onboarding.finish": "Open app",
            "onboarding.welcome_headline": "HiAir — heat & air wellness assistant",
            "onboarding.welcome_body": "Personal risk, safe windows, and daily guidance.",
            "onboarding.value_headline": "What you get",
            "onboarding.value_body": "HiAir explains heat and AQI risk for your profile.",
            "onboarding.persona_headline": "Who are you?",
            "onboarding.persona_body": "Wellness guidance only — not medical advice.",
            "onboarding.location_headline": "Where are you?",
            "onboarding.location_body": "Location powers local heat and AQI forecasts.",
            "onboarding.notifications_headline": "Risk notifications",
            "onboarding.notifications_body": "Alerts when risk rises for your profile.",
            "onboarding.health_headline": "Health data (optional)",
            "onboarding.health_body": "Steps, heart rate and sleep will personalize guidance later (foundation).",
            "onboarding.health_optional": "HiAir is wellness guidance, not medical advice.",
            "onboarding.first_result_headline": "Your first result",
            "onboarding.step.welcome": "Step 1 of 7",
            "onboarding.step.value": "Step 2 of 7",
            "onboarding.step.persona": "Step 3 of 7",
            "onboarding.step.location": "Step 4 of 7",
            "onboarding.step.notifications": "Step 5 of 7",
            "onboarding.step.health": "Step 6 of 7",
            "onboarding.step.first_result": "Step 7 of 7",
            "dashboard.morning_briefing": "Morning Briefing",
            "dashboard.risk_breakdown": "Risk breakdown",
            "dashboard.share": "Share",
            "dashboard.fetch": "Tap refresh to load data.",
            "dashboard.no_actions": "No actions available.",
            "privacy.title": "Privacy",
            "privacy.export": "Export my data",
            "privacy.delete": "Delete my data",
            "privacy.wellness_notice": "HiAir is wellness guidance, not medical advice.",
            "privacy.health_explanation": "HealthKit data is optional. Foundation only — metric reads ship after entitlements.",
            "privacy.policy": "Privacy Policy",
            "privacy.terms": "Terms of Service",
            "privacy.auth_required": "Sign in required for export/delete (not available in guest mode).",
            "privacy.export_ok": "Export completed.",
            "privacy.export_failed": "Export failed.",
            "privacy.delete_ok": "Data deleted.",
            "privacy.delete_failed": "Delete failed.",
            "privacy.delete_confirm_title": "Delete all data?",
            "privacy.delete_confirm_body": "This is irreversible. Server requires DELETE confirmation.",
            "privacy.delete_confirm_yes": "Delete",
            "privacy.delete_confirm_no": "Cancel",
            "health.foundation_only": "Foundation only: steps/heart rate/sleep reads come after entitlements and device QA.",
            "health.skipped": "Health data not used.",
            "health.not_available": "HealthKit unavailable.",
            "health.permission_needed": "HealthKit permissions can be enabled later.",
            "share.title": "HiAir — air & heat risk",
            "share.risk": "Risk",
            "share.best_walk": "Best walk window",
            "share.warning": "Warning",
            "share.generated_by": "Generated by HiAir",
            "dashboard.title": "Daily Air Intelligence",
            "common.city_updated": "Barcelona • Updated 2 min ago",
            "dashboard.subtitle": "Live risk, alerts and AI insights in one place.",
            "dashboard.greeting": "Good morning, Alex",
            "dashboard.improving": "Air quality is improving. Plan outdoors after 16:30.",
            "dashboard.current_risk": "Current risk",
            "dashboard.current_risk_title": "Current risk",
            "dashboard.badge_moderate": "MODERATE",
            "dashboard.no_safe_window": "No safe windows in the next hours.",
            "dashboard.error": "Unable to load data.",
            "dashboard.recommended_actions": "Recommended actions",
            "dashboard.no_actions": "No actions available.",
            "dashboard.safe_window": "Safe window",
            "dashboard.safe_windows": "Safe windows",
            "dashboard.auto_updates": "Auto-updates by forecast",
            "dashboard.do_now": "Do this now",
            "dashboard.action_1": "Avoid direct sun from 10:00 to 15:00",
            "dashboard.action_2": "Hydrate every 45 minutes",
            "dashboard.action_3": "Best outdoor window 16:30 - 19:00",
            "dashboard.recompute": "Recompute risk now",
            "dashboard.log_symptoms": "Log symptoms now",
            "dashboard.loading": "Loading...",
            "planner.title": "Daily Planner",
            "planner.subtitle": "Complete recommendations based on your profile and air trends.",
            "planner.safe_windows": "Safe windows",
            "planner.ventilation_windows": "Ventilation windows",
            "planner.hourly_risk": "Hourly risk",
            "planner.hourly": "Hour-by-hour",
            "planner.refresh": "Refresh planner",
            "planner.apply": "Apply this plan",
            "planner.loading": "Loading...",
            "planner.profile_required": "Profile ID is required.",
            "planner.failed": "Failed to load planner.",
            "symptoms.title": "Symptoms Log",
            "symptoms.subtitle": "Track how you feel for better personalized guidance.",
            "symptoms.profile_id": "Profile ID",
            "symptoms.cough": "Cough",
            "symptoms.wheeze": "Wheeze",
            "symptoms.headache": "Headache",
            "symptoms.fatigue": "Fatigue",
            "symptoms.sleep_quality": "Sleep quality",
            "symptoms.quick_intensity": "Quick intensity",
            "symptoms.quick_breath": "Quick: Breath",
            "symptoms.quick_headache": "Quick: Headache",
            "symptoms.save": "Save Symptoms",
            "symptoms.submit": "Submit symptoms",
            "symptoms.saving": "Saving...",
            "symptoms.saved_at": "Saved at",
            "symptoms.save_failed": "Failed to save symptoms.",
            "symptoms.quick_saved": "Quick symptom saved.",
            "symptoms.quick_failed": "Failed to save quick symptom.",
            "settings.ai_observability": "AI Observability",
            "settings.subtitle": "Manage notifications, subscriptions and AI observability.",
            "settings.notifications": "Notifications",
            "settings.push": "Enable push alerts",
            "settings.profile_alerting": "Profile-based alerting",
            "settings.alert_threshold": "Alert threshold",
            "settings.threshold_medium": "Medium",
            "settings.threshold_high": "High",
            "settings.threshold_very_high": "Very high",
            "settings.quiet_start": "Quiet start",
            "settings.quiet_end": "Quiet end",
            "settings.profile_defaults": "Profile defaults",
            "settings.persona": "Persona",
            "settings.persona_adult": "Adult",
            "settings.persona_child": "Child",
            "settings.persona_elderly": "Elderly",
            "settings.persona_asthma": "Asthma",
            "settings.persona_allergy": "Allergy",
            "settings.persona_runner": "Runner",
            "settings.persona_worker": "Outdoor worker",
            "settings.language": "Language",
            "settings.language_ru": "Russian",
            "settings.language_en": "English",
            "settings.window_24h": "24h",
            "settings.window_72h": "72h",
            "settings.sync": "Sync",
            "settings.loading": "Loading...",
            "settings.saving": "Saving...",
            "settings.subscription": "Subscription",
            "settings.security_privacy": "Security & Privacy",
            "settings.plan": "Plan",
            "settings.status": "Status",
            "settings.sync_now": "Save settings & sync",
            "settings.advanced_controls": "Advanced chart controls",
            "settings.load": "Load settings",
            "settings.save": "Save settings",
            "settings.load_plans": "Load plans",
            "settings.load_subscription": "Load subscription",
            "settings.activate_subscription": "Activate subscription",
            "settings.cancel_subscription": "Cancel subscription",
            "settings.user_id_required": "Enter user ID.",
            "settings.loaded": "Settings loaded.",
            "settings.load_failed": "Failed to load settings.",
            "settings.saved": "Settings saved.",
            "settings.save_failed": "Failed to save settings.",
            "settings.plans_loaded": "Plans loaded.",
            "settings.plans_load_failed": "Failed to load plans.",
            "settings.subscription_loaded": "Subscription loaded.",
            "settings.subscription_load_failed": "Failed to load subscription.",
            "settings.subscription_activated": "Subscription activated.",
            "settings.subscription_activate_failed": "Failed to activate subscription.",
            "settings.subscription_canceled": "Subscription canceled.",
            "settings.subscription_cancel_failed": "Failed to cancel subscription.",
            "settings.subscription_status_active": "active",
            "settings.subscription_status_inactive": "inactive",
            "settings.subscription_status_canceled": "canceled",
            "settings.logged_out": "Logged out.",
            "settings.log_out": "Log out",
            "settings.user_id": "User ID",
            "settings.token": "Access token",
            "settings.window": "Window",
            "settings.metric": "Metric",
            "settings.metric.total": "Total",
            "settings.metric.fallback": "Fallback",
            "settings.metric.guardrail": "Guardrail",
            "settings.metric.errors": "Errors (sum)",
            "settings.metric.timeout": "Timeout",
            "settings.metric.network": "Network",
            "settings.metric.server": "Server",
            "settings.mode": "Mode",
            "settings.mode.bars": "Bars",
            "settings.mode.line": "Line",
            "settings.range": "Range",
            "settings.axis": "Axis",
            "settings.request_status": "Request status",
            "settings.request_loading": "Loading...",
            "settings.request_idle": "Idle",
            "settings.request_timeout": "Timeout",
            "settings.last_updated": "Last updated",
            "settings.ai_retry_now": "Retry now",
            "settings.ai_retry_later": "Try later",
            "settings.ai_timeout_inline": "AI observability request timed out.",
            "settings.ai_network_inline": "Network unavailable. Check your connection and retry.",
            "settings.ai_server_inline": "Server is temporarily unavailable. Please try later.",
            "settings.ai_request_failed_inline": "AI observability request failed.",
            "settings.ai_top_prompt": "Top prompt version",
            "settings.ai_top_model": "Top model",
            "settings.ai_error_counts": "Errors",
            "settings.ai_error_type.timeout": "timeout",
            "settings.ai_error_type.network": "network",
            "settings.ai_error_type.server": "server",
            "settings.ai_error_type.other": "other",
            "settings.ai_events": "AI events",
            "settings.ai_fallback": "fallback",
            "settings.ai_guardrail_blocks": "guardrail blocks",
            "settings.ai_latest_hour": "Latest hour",
            "settings.ai_blocks_short": "blocks",
            "settings.ai_no_trend": "No trend points for selected period.",
            "settings.ai_loaded": "AI observability loaded.",
            "settings.ai_failed": "Failed to load AI observability.",
            "settings.ai_request_failed": "AI observability request failed.",
            "settings.load_ai_summary": "Load AI Summary",
            "settings.loading_ai_metrics": "Loading AI metrics...",
            "feedback.title": "Send Feedback",
            "feedback.subtitle": "Help us improve HiAir for the first users.",
            "feedback.liked": "What you liked",
            "feedback.confusing": "What was confusing",
            "feedback.broken": "What broke",
            "feedback.email_optional": "Email (optional)",
            "feedback.send": "Send",
            "feedback.sent_ok": "Thanks! Feedback sent.",
            "feedback.sent_failed": "Failed to send feedback.",
            "feedback.empty": "Fill at least one field.",
            "kpi.load": "First-user KPI",
            "kpi.load_failed": "Failed to load KPI dashboard."
        ]
    ]
}

extension AppSession {
    func l(_ key: String) -> String {
        HiAirL10n.t(key, lang: preferredLanguage)
    }
}
